services:
  postgres:
    image: postgres:16.4
    container_name: memento_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - memento_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 20
    networks:
      - memento_network

  migrate:
    image: kukymbr/goose-docker:3.26.0
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations:ro
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"
    command: ["-dir", "/migrations", "up"]
    restart: "no"
    networks:
      - memento_network

volumes:
  memento_pgdata:

networks:
  memento_network:
    external: true